# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xop7IKIlyr4knZteJIXutB5XxjhuzCLd
"""

!pip install firebase-admin pandas

from google.colab import files

uploaded = files.upload()

import os
os.listdir()

from google.colab import files
files.upload()

import os
os.listdir("/content")

import firebase_admin
from firebase_admin import credentials, firestore

cred = credentials.Certificate(
    "practica-learning-adolfo-1961f-firebase-adminsdk-fbsvc-04b3aa3a4b.json"
)

# Evitar inicialización duplicada
if not firebase_admin._apps:
    firebase_admin.initialize_app(cred)

db = firestore.client()

print("🔥 Firebase inicializado correctamente")

import pandas as pd

df = pd.read_csv("movies.csv")

df.head()

!pip install streamlit pyngrok firebase-admin

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import firebase_admin
# from firebase_admin import credentials, firestore
# 
# 
# # CONFIGURACIÓN DE LA APP
# st.set_page_config(page_title="Movies Dashboard", layout="wide")
# 
# st.title("🎬 Movies Dashboard")
# 
# 
# # CONEXIÓN A FIRESTORE
# @st.cache_resource
# def init_firestore():
#     if not firebase_admin._apps:
#         cred = credentials.Certificate("practica-learning-adolfo-1961f-firebase-adminsdk-fbsvc-04b3aa3a4b.json")
#         firebase_admin.initialize_app(cred)
#     return firestore.client()
# 
# db = init_firestore()
# 
# 
# # CARGAR DATOS
# @st.cache_data
# def load_data():
#     docs = db.collection("movies").stream()
#     data = [doc.to_dict() for doc in docs]
#     return pd.DataFrame(data)
# 
# df = load_data()
# 
# 
# # VALIDAR CARGA
# st.subheader("Data Preview")
# 
# if df.empty:
#     st.warning("No data found in Firestore")
# else:
#     st.success(f"Loaded {len(df)} records")
#     st.dataframe(df)
# 
# 
# # SIDEBAR
# 
# st.sidebar.header("Filters")
# 
# filtered_df = df.copy()
# 
# #  Buscador por título
# search = st.sidebar.text_input("Search by title")
# 
# if search and "title" in df.columns:
#     filtered_df = filtered_df[
#         filtered_df["title"].str.contains(search, case=False, na=False)
#     ]
# 
# #  Filtro por género
# if "genre" in df.columns:
#     genre = st.sidebar.selectbox(
#         "Select Genre",
#         options=["All"] + list(df["genre"].dropna().unique())
#     )
# 
#     if genre != "All":
#         filtered_df = filtered_df[filtered_df["genre"] == genre]
# 
# #  Filtro por director
# if "director" in df.columns:
#     director = st.sidebar.selectbox(
#         "Select Director",
#         options=["All"] + list(df["director"].dropna().unique())
#     )
# 
#     if director != "All":
#         filtered_df = filtered_df[filtered_df["director"] == director]
# 
# # Checkbox para mostrar/ocultar tabla
# show_data = st.sidebar.checkbox("Show filtered data")
# 
# # MÉTRICAS
# st.subheader("Metrics")
# 
# col1, col2 = st.columns(2)
# 
# col1.metric("Total Movies", len(filtered_df))
# 
# if "rating" in df.columns:
#     col2.metric("Average Rating", round(filtered_df["rating"].mean(), 2))
# 
# 
# # GRÁFICA
# st.subheader("Ratings Distribution")
# 
# if "rating" in df.columns:
#     st.bar_chart(filtered_df["rating"])
# 
# 
# 
# if show_data:
#     st.subheader("Filtered Data")
#     st.dataframe(filtered_df)
# 
#

batch = db.batch()
for i, row in df.iterrows():
    ref = db.collection("movies").document(str(i))
    batch.set(ref, row.to_dict())

batch.commit()